package com.bs.glr.bean;

import lombok.Data;

import java.util.Date;
@Data
public class BsBookInfo {
    String sortName;
    String addressName;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.publication_date
     *
     * @mbg.generated
     */
    private Date publicationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.press
     *
     * @mbg.generated
     */
    private String press;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.book_name
     *
     * @mbg.generated
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.sort_id
     *
     * @mbg.generated
     */
    private Integer sortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.address_id
     *
     * @mbg.generated
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.rfid_id
     *
     * @mbg.generated
     */
    private String rfidId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.select_number
     *
     * @mbg.generated
     */
    private Integer selectNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.photo_url
     *
     * @mbg.generated
     */
    private String photoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.book_status
     *
     * @mbg.generated
     */
    private String bookStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.book_count
     *
     * @mbg.generated
     */
    private String bookCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.raters_number
     *
     * @mbg.generated
     */
    private Integer ratersNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.raters
     *
     * @mbg.generated
     */
    private String raters;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_book_info.isbn
     *
     * @mbg.generated
     */
    private String isbn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.id
     *
     * @return the value of bs_book_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.id
     *
     * @param id the value for bs_book_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.create_time
     *
     * @return the value of bs_book_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.create_time
     *
     * @param createTime the value for bs_book_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.publication_date
     *
     * @return the value of bs_book_info.publication_date
     *
     * @mbg.generated
     */
    public Date getPublicationDate() {
        return publicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.publication_date
     *
     * @param publicationDate the value for bs_book_info.publication_date
     *
     * @mbg.generated
     */
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.author
     *
     * @return the value of bs_book_info.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.author
     *
     * @param author the value for bs_book_info.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.press
     *
     * @return the value of bs_book_info.press
     *
     * @mbg.generated
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.press
     *
     * @param press the value for bs_book_info.press
     *
     * @mbg.generated
     */
    public void setPress(String press) {
        this.press = press == null ? null : press.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.book_name
     *
     * @return the value of bs_book_info.book_name
     *
     * @mbg.generated
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.book_name
     *
     * @param bookName the value for bs_book_info.book_name
     *
     * @mbg.generated
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.sort_id
     *
     * @return the value of bs_book_info.sort_id
     *
     * @mbg.generated
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.sort_id
     *
     * @param sortId the value for bs_book_info.sort_id
     *
     * @mbg.generated
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.address_id
     *
     * @return the value of bs_book_info.address_id
     *
     * @mbg.generated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.address_id
     *
     * @param addressId the value for bs_book_info.address_id
     *
     * @mbg.generated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.rfid_id
     *
     * @return the value of bs_book_info.rfid_id
     *
     * @mbg.generated
     */
    public String getRfidId() {
        return rfidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.rfid_id
     *
     * @param rfidId the value for bs_book_info.rfid_id
     *
     * @mbg.generated
     */
    public void setRfidId(String rfidId) {
        this.rfidId = rfidId == null ? null : rfidId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.select_number
     *
     * @return the value of bs_book_info.select_number
     *
     * @mbg.generated
     */
    public Integer getSelectNumber() {
        return selectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.select_number
     *
     * @param selectNumber the value for bs_book_info.select_number
     *
     * @mbg.generated
     */
    public void setSelectNumber(Integer selectNumber) {
        this.selectNumber = selectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.photo_url
     *
     * @return the value of bs_book_info.photo_url
     *
     * @mbg.generated
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.photo_url
     *
     * @param photoUrl the value for bs_book_info.photo_url
     *
     * @mbg.generated
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.book_status
     *
     * @return the value of bs_book_info.book_status
     *
     * @mbg.generated
     */
    public String getBookStatus() {
        return bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.book_status
     *
     * @param bookStatus the value for bs_book_info.book_status
     *
     * @mbg.generated
     */
    public void setBookStatus(String bookStatus) {
        this.bookStatus = bookStatus == null ? null : bookStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.book_count
     *
     * @return the value of bs_book_info.book_count
     *
     * @mbg.generated
     */
    public String getBookCount() {
        return bookCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.book_count
     *
     * @param bookCount the value for bs_book_info.book_count
     *
     * @mbg.generated
     */
    public void setBookCount(String bookCount) {
        this.bookCount = bookCount == null ? null : bookCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.raters_number
     *
     * @return the value of bs_book_info.raters_number
     *
     * @mbg.generated
     */
    public Integer getRatersNumber() {
        return ratersNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.raters_number
     *
     * @param ratersNumber the value for bs_book_info.raters_number
     *
     * @mbg.generated
     */
    public void setRatersNumber(Integer ratersNumber) {
        this.ratersNumber = ratersNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.raters
     *
     * @return the value of bs_book_info.raters
     *
     * @mbg.generated
     */
    public String getRaters() {
        return raters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.raters
     *
     * @param raters the value for bs_book_info.raters
     *
     * @mbg.generated
     */
    public void setRaters(String raters) {
        this.raters = raters == null ? null : raters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_book_info.isbn
     *
     * @return the value of bs_book_info.isbn
     *
     * @mbg.generated
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_book_info.isbn
     *
     * @param isbn the value for bs_book_info.isbn
     *
     * @mbg.generated
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }
}