package com.bs.glr.bean;

import java.util.Date;

public class BsBorrow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.book_id
     *
     * @mbg.generated
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.boorrw_status
     *
     * @mbg.generated
     */
    private String boorrwStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.get_time
     *
     * @mbg.generated
     */
    private Date getTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_borrow.return_time
     *
     * @mbg.generated
     */
    private Date returnTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.id
     *
     * @return the value of bs_borrow.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.id
     *
     * @param id the value for bs_borrow.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.uid
     *
     * @return the value of bs_borrow.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.uid
     *
     * @param uid the value for bs_borrow.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.book_id
     *
     * @return the value of bs_borrow.book_id
     *
     * @mbg.generated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.book_id
     *
     * @param bookId the value for bs_borrow.book_id
     *
     * @mbg.generated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.end_time
     *
     * @return the value of bs_borrow.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.end_time
     *
     * @param endTime the value for bs_borrow.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.boorrw_status
     *
     * @return the value of bs_borrow.boorrw_status
     *
     * @mbg.generated
     */
    public String getBoorrwStatus() {
        return boorrwStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.boorrw_status
     *
     * @param boorrwStatus the value for bs_borrow.boorrw_status
     *
     * @mbg.generated
     */
    public void setBoorrwStatus(String boorrwStatus) {
        this.boorrwStatus = boorrwStatus == null ? null : boorrwStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.get_time
     *
     * @return the value of bs_borrow.get_time
     *
     * @mbg.generated
     */
    public Date getGetTime() {
        return getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.get_time
     *
     * @param getTime the value for bs_borrow.get_time
     *
     * @mbg.generated
     */
    public void setGetTime(Date getTime) {
        this.getTime = getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_borrow.return_time
     *
     * @return the value of bs_borrow.return_time
     *
     * @mbg.generated
     */
    public Date getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_borrow.return_time
     *
     * @param returnTime the value for bs_borrow.return_time
     *
     * @mbg.generated
     */
    public void setReturnTime(Date returnTime) {
        this.returnTime = returnTime;
    }
}