package com.bs.glr.bean;

public class BsScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_score.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_score.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_score.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_score.id
     *
     * @return the value of bs_score.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_score.id
     *
     * @param id the value for bs_score.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_score.uid
     *
     * @return the value of bs_score.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_score.uid
     *
     * @param uid the value for bs_score.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_score.score
     *
     * @return the value of bs_score.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_score.score
     *
     * @param score the value for bs_score.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}