package com.bs.glr.bean;

public class BsVerdueRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_verdue_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_verdue_record.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_verdue_record.borrow_id
     *
     * @mbg.generated
     */
    private Integer borrowId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_verdue_record.id
     *
     * @return the value of bs_verdue_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_verdue_record.id
     *
     * @param id the value for bs_verdue_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_verdue_record.uid
     *
     * @return the value of bs_verdue_record.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_verdue_record.uid
     *
     * @param uid the value for bs_verdue_record.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_verdue_record.borrow_id
     *
     * @return the value of bs_verdue_record.borrow_id
     *
     * @mbg.generated
     */
    public Integer getBorrowId() {
        return borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_verdue_record.borrow_id
     *
     * @param borrowId the value for bs_verdue_record.borrow_id
     *
     * @mbg.generated
     */
    public void setBorrowId(Integer borrowId) {
        this.borrowId = borrowId;
    }
}