package com.bs.glr.bean;

import java.util.Date;

public class StmData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stm_data.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stm_data.stm_data
     *
     * @mbg.generated
     */
    private String stmData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stm_data.device_id
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stm_data.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stm_data.id
     *
     * @return the value of stm_data.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stm_data.id
     *
     * @param id the value for stm_data.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stm_data.stm_data
     *
     * @return the value of stm_data.stm_data
     *
     * @mbg.generated
     */
    public String getStmData() {
        return stmData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stm_data.stm_data
     *
     * @param stmData the value for stm_data.stm_data
     *
     * @mbg.generated
     */
    public void setStmData(String stmData) {
        this.stmData = stmData == null ? null : stmData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stm_data.device_id
     *
     * @return the value of stm_data.device_id
     *
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stm_data.device_id
     *
     * @param deviceId the value for stm_data.device_id
     *
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stm_data.create_date
     *
     * @return the value of stm_data.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stm_data.create_date
     *
     * @param createDate the value for stm_data.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}