package com.bs.glr.mapper;

import com.bs.glr.bean.BsBookAddress;
import com.bs.glr.bean.BsBookAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsBookAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_address
     *
     * @mbg.generated
     */
    long countByExample(BsBookAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_address
     *
     * @mbg.generated
     */
    int deleteByExample(BsBookAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_address
     *
     * @mbg.generated
     */
    int insert(BsBookAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_address
     *
     * @mbg.generated
     */
    int insertSelective(BsBookAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_address
     *
     * @mbg.generated
     */
    List<BsBookAddress> selectByExample(BsBookAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_address
     *
     * @mbg.generated
     */
    BsBookAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BsBookAddress record, @Param("example") BsBookAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BsBookAddress record, @Param("example") BsBookAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BsBookAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_book_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BsBookAddress record);
}