package com.bs.glr.mapper;

import com.bs.glr.bean.BsBorrow;
import com.bs.glr.bean.BsBorrowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsBorrowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_borrow
     *
     * @mbg.generated
     */
    long countByExample(BsBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_borrow
     *
     * @mbg.generated
     */
    int deleteByExample(BsBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_borrow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_borrow
     *
     * @mbg.generated
     */
    int insert(BsBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_borrow
     *
     * @mbg.generated
     */
    int insertSelective(BsBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_borrow
     *
     * @mbg.generated
     */
    List<BsBorrow> selectByExample(BsBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_borrow
     *
     * @mbg.generated
     */
    BsBorrow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_borrow
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BsBorrow record, @Param("example") BsBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_borrow
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BsBorrow record, @Param("example") BsBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_borrow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BsBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_borrow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BsBorrow record);
}